server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Patronage_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 243417
  jpa:
    show-sql: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 2000s
    jedis:
      pool:
        max-idle: 8
        max-wait:
        min-idle: 0
        max-active: 8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.PatronageSystem.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.PatronageSystem.mapper: debug
