spring:
  thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 243417
    url: jdbc:mysql://127.0.0.1:3306/ceshi?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
  jpa:
    show-sql: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 2000s
    jedis:
      pool:
        max-idle: 8
        max-wait:
        min-idle: 0
        max-active: 8






